spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

alibaba:
  cloud:
    access-key: LTAI5tBQPRdinrhu4m5RCGiD
    secret-key: 6vq1RCzPcSWdKEQWmKjbAsgwDaZ0X0
    oss:
      endpoint: oss-cn-hangzhou.aliyuncs.com